---
application:
  name: "mobile-feso-api"
  project: "mobile-feso"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "database"
  version: "4.4"
routers:
- name: "main-mobile-feso-api"
  routes:
  - application_name: "mobile-feso-api"
    paths:
    - "/*"
